CC = g++
LIBS = -Llib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
INCLUDES = -Iinclude -Iinclude/sdl -Iinclude/headers
DEPS = main.o entity.o renderwindow.o vector.o clock.o

pawng: $(DEPS)
	$(CC) $(INCLUDES) -g -o $@ $(DEPS) $(LIBS)

%.o: src/%.cpp
	$(CC) -c $(INCLUDES) $< -o $@ $(LIBS)